# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addquestion.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import sqlite3
import questionbank


class Ui_add_question(object):
    def setupUi(self, add_question):
        add_question.setObjectName("add_question")
        add_question.resize(597, 310)
        self.centralwidget = QtWidgets.QWidget(add_question)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(30, 20, 511, 111))
        self.groupBox.setObjectName("groupBox")
        self.textEdit = QtWidgets.QTextEdit(self.groupBox)
        self.textEdit.setGeometry(QtCore.QRect(20, 30, 471, 71))
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(60, 260, 461, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.save_question_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.save_question_button.setObjectName("save_question_button")
        self.horizontalLayout.addWidget(self.save_question_button)
        self.cancel_question_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.cancel_question_button.setObjectName("cancel_question_button")
        self.horizontalLayout.addWidget(self.cancel_question_button)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(30, 140, 511, 91))
        self.groupBox_2.setObjectName("groupBox_2")
        self.textEdit_2 = QtWidgets.QTextEdit(self.groupBox_2)
        self.textEdit_2.setGeometry(QtCore.QRect(20, 30, 471, 51))
        self.textEdit_2.setObjectName("textEdit_2")
        add_question.setCentralWidget(self.centralwidget)

        self.retranslateUi(add_question)
        QtCore.QMetaObject.connectSlotsByName(add_question)
        ##################################################################
        self.save_question_button.clicked.connect(self.addquestion)
        self.cancel_question_button.clicked.connect(add_question.close)
        self.save_question_button.clicked.connect(add_question.close)
        self.cancel_question_button.clicked.connect(self.showquestionbank)
        self.save_question_button.clicked.connect(self.showquestionbank)


    def addquestion(self):
        id = ''
        question=''
        answer=''
        modify=''

        question=self.textEdit.toPlainText()
        answer=self.textEdit_2.toPlainText()
        print(question)
        
        if question != '' and answer !='':
            try:
                con = sqlite3.connect("userlist.db",timeout=10)
                cur = con.cursor()
                cur.execute("INSERT INTO questionbank(question,answer) VALUES (?,?)",(question,answer))
                con.commit()
                cur.close()
                con.close()
                self.showMessageBox('Success', 'Question has been added!')
            except Exception:
                self.showMessageBox('Database Error','Could not load the database')
        else:
                self.showMessageBox('Error','Enter some values!')
    def showquestionbank(self):
        self.questionbankWindow = QtWidgets.QMainWindow()
        self.ui = questionbank.Ui_Question_bank()
        self.ui.setupUi(self.questionbankWindow)
        self.questionbankWindow.show()

    def showMessageBox(self,title,message):
        msgBox = QtWidgets.QMessageBox()
        msgBox.setIcon(QtWidgets.QMessageBox.Warning)
        msgBox.setWindowTitle(title)
        msgBox.setText(message)
        msgBox.setStandardButtons(QtWidgets.QMessageBox.Ok)
        msgBox.exec_()

    def retranslateUi(self, add_question):
        _translate = QtCore.QCoreApplication.translate
        add_question.setWindowTitle(_translate("add_question", "Add Questions"))
        self.groupBox.setTitle(_translate("add_question", "Question"))
        self.save_question_button.setText(_translate("add_question", "Save"))
        self.cancel_question_button.setText(_translate("add_question", "Cancel"))
        self.groupBox_2.setTitle(_translate("add_question", "Answer"))

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    addquestionpage = QtWidgets.QMainWindow()
    ui = Ui_add_question()
    ui.setupUi(addquestionpage)
    addquestionpage.show()
    sys.exit(app.exec_())