# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addstudent.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import sqlite3
import studentlist

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(297, 429)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 340, 281, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 30, 121, 16))
        self.label.setObjectName("label")
        self.name_line = QtWidgets.QLineEdit(self.centralwidget)
        self.name_line.setGeometry(QtCore.QRect(50, 80, 189, 22))
        self.name_line.setObjectName("name_line")
        self.firstname_label = QtWidgets.QLabel(self.centralwidget)
        self.firstname_label.setGeometry(QtCore.QRect(50, 110, 41, 20))
        self.firstname_label.setObjectName("firstname_label")
        self.username_student_line = QtWidgets.QLineEdit(self.centralwidget)
        self.username_student_line.setGeometry(QtCore.QRect(50, 160, 189, 22))
        self.username_student_line.setObjectName("username_student_line")
        self.password_student_line = QtWidgets.QLineEdit(self.centralwidget)
        self.password_student_line.setGeometry(QtCore.QRect(50, 240, 189, 22))
        self.password_student_line.setObjectName("password_student_line")
        self.username_student_label = QtWidgets.QLabel(self.centralwidget)
        self.username_student_label.setGeometry(QtCore.QRect(50, 190, 71, 20))
        self.username_student_label.setObjectName("username_student_label")
        self.password_student_label = QtWidgets.QLabel(self.centralwidget)
        self.password_student_label.setGeometry(QtCore.QRect(50, 270, 71, 20))
        self.password_student_label.setObjectName("password_student_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.password_student_line.setEchoMode(QtWidgets.QLineEdit.Password)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        ################################################################
        self.pushButton_2.clicked.connect(MainWindow.close)
        ################################################################
        self.pushButton.clicked.connect(self.addstudent)
        self.pushButton.clicked.connect(MainWindow.close)
        self.pushButton.clicked.connect(self.showstudentlist)
        self.pushButton_2.clicked.connect(self.showstudentlist)
    
    def addstudent(self):
        usertype='student'
        name=''
        username=''
        password=''

        name=self.name_line.text()
        username=self.username_student_line.text()
        password=self.password_student_line.text()
        if username != '' and password !='' and name !='':
            try:
                con = sqlite3.connect("userlist.db",timeout=10)
                cur = con.cursor()
                cur.execute("INSERT INTO users(TYPE,NAME,USERNAME,PASSWORD) VALUES (?,?,?,?)",(usertype,name,username,password))
                con.commit()
                cur.close()
                con.close()
                self.showMessageBox('Success', 'User has been registered as student')
            except Exception:
                self.showMessageBox('Database Error','Could not register the the database')
        else:
                self.showMessageBox('Error','Enter some values!')


        
    def showMessageBox(self,title,message):
        msgBox = QtWidgets.QMessageBox()
        msgBox.setIcon(QtWidgets.QMessageBox.Warning)
        msgBox.setWindowTitle(title)
        msgBox.setText(message)
        msgBox.setStandardButtons(QtWidgets.QMessageBox.Ok)
        msgBox.exec_()

    def showstudentlist(self):
        self.studentlistwindow = QtWidgets.QMainWindow()
        self.ui = studentlist.Ui_MainWindow()
        self.ui.setupUi(self.studentlistwindow)
        self.studentlistwindow.show()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Add Student"))
        self.pushButton.setText(_translate("MainWindow", "Add"))
        self.pushButton_2.setText(_translate("MainWindow", "Cancel"))
        self.label.setText(_translate("MainWindow", "Student Information"))
        self.firstname_label.setText(_translate("MainWindow", "NAME"))
        self.username_student_label.setText(_translate("MainWindow", "USERNAME"))
        self.password_student_label.setText(_translate("MainWindow", "PASSWORD"))

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    addstudentWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(addstudentWindow)
    addstudentWindow.show()
    sys.exit(app.exec_())