# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'adminmain.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import login
import studentlist
import questionbank
import sys
import sqlite3


class Ui_admin_main(object):
    def setupUi(self, admin_main):
        admin_main.setObjectName("admin_main")
        admin_main.resize(482, 142)
        self.centralwidget = QtWidgets.QWidget(admin_main)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 10, 61, 16))
        self.label.setObjectName("label")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(290, 20, 160, 98))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.student_list_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.student_list_button.setObjectName("student_list_button")
        self.verticalLayout.addWidget(self.student_list_button)
        self.question_bank_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.question_bank_button.setObjectName("question_bank_button")
        self.verticalLayout.addWidget(self.question_bank_button)
        self.logout_admin_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.logout_admin_button.setObjectName("logout_admin_button")
        self.verticalLayout.addWidget(self.logout_admin_button)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 40, 251, 81))
        self.groupBox.setObjectName("groupBox")
        self.user_label = QtWidgets.QLabel(self.groupBox)
        self.user_label.setGeometry(QtCore.QRect(10, 30, 55, 16))
        self.user_label.setObjectName("user_label")
        self.username_label = QtWidgets.QLabel(self.groupBox)
        self.username_label.setGeometry(QtCore.QRect(80, 30, 151, 16))
        self.username_label.setObjectName("username_label")
        self.name_label = QtWidgets.QLabel(self.groupBox)
        self.name_label.setGeometry(QtCore.QRect(10, 50, 55, 16))
        self.name_label.setObjectName("name_label")
        self.nameuser_label = QtWidgets.QLabel(self.groupBox)
        self.nameuser_label.setGeometry(QtCore.QRect(80, 50, 161, 16))
        self.nameuser_label.setObjectName("nameuser_label")
        admin_main.setCentralWidget(self.centralwidget)
        self.actionLogout = QtWidgets.QAction(admin_main)
        self.actionLogout.setObjectName("actionLogout")
        self.actionExit = QtWidgets.QAction(admin_main)
        self.actionExit.setObjectName("actionExit")
        QtWidgets.qApp.processEvents()
        self.retranslateUi(admin_main)
        QtCore.QMetaObject.connectSlotsByName(admin_main)
        ###########################################################################
        self.logout_admin_button.clicked.connect(self.loginpageShow)
        self.logout_admin_button.clicked.connect(admin_main.close)
        ###########################################################################
        self.student_list_button.clicked.connect(self.studentlistShow)
      #  self.student_list_button.clicked.connect(self.movemainpage)
        self.student_list_button.clicked.connect(admin_main.close)
        ###########################################################################
        self.question_bank_button.clicked.connect(self.questionbankShow)
       # self.question_bank_button.clicked.connect(self.movemainpage)
        self.question_bank_button.clicked.connect(admin_main.close)
        ###########################################################################
        usertype='null'
        name='null'
        username1='null'
        password1='null'
        try:
            con = sqlite3.connect("userlist.db",timeout=10)
            cur = con.cursor()
            cur.execute('SELECT * FROM users WHERE ID=1')
            data = cur.fetchall()
            con.commit
            for row in data:
                usertype = row[1]
                name = row[2]
                username1 = row[3]
                password1 = row[4]
            con.close
            self.username_label.setText(username1)
            self.nameuser_label.setText(name)
        except Exception:
            self.showMessageBox('Database Error','Could not access the database')

        ###########################################################################

        ###########################################################################

    #def connection(self):

    #def movemainpage(self):
       # self.adminmainpage2 = QtWidgets.QMainWindow()
       # self.ui = Ui_admin_main()
      #  self.ui.setupUi(self.adminmainpage2)
      #  self.adminmainpage2.show()
     #   self.adminmainpage2.move(50,50)
        
    def loginpageShow(self):
        self.loginpageWindow = QtWidgets.QMainWindow()
        self.ui = login.Ui_LOGINPAGE()
        self.ui.setupUi(self.loginpageWindow)
        self.loginpageWindow.show()   

    def studentlistShow(self):
        self.studentlistWindow = QtWidgets.QMainWindow()
        self.ui = studentlist.Ui_MainWindow()
        self.ui.setupUi(self.studentlistWindow)
        self.studentlistWindow.show()      

    def questionbankShow(self):
        self.questionbankWindow = QtWidgets.QMainWindow()
        self.ui = questionbank.Ui_Question_bank()
        self.ui.setupUi(self.questionbankWindow)
        self.questionbankWindow.show()  

    def showMessageBox(self,title,message):
        msgBox = QtWidgets.QMessageBox()
        msgBox.setIcon(QtWidgets.QMessageBox.Warning)
        msgBox.setWindowTitle(title)
        msgBox.setText(message)
        msgBox.setStandardButtons(QtWidgets.QMessageBox.Ok)
        msgBox.exec_()

     

    def retranslateUi(self, admin_main):
        _translate = QtCore.QCoreApplication.translate
        admin_main.setWindowTitle(_translate("admin_main", "Online Reviewer"))
        self.label.setText(_translate("admin_main", "WELCOME"))
        self.student_list_button.setText(_translate("admin_main", "STUDENT LIST"))
        self.question_bank_button.setText(_translate("admin_main", "QUESTION BANK"))
        self.logout_admin_button.setText(_translate("admin_main", "LOGOUT"))
        self.groupBox.setTitle(_translate("admin_main", "Online Reviewer"))
        self.user_label.setText(_translate("admin_main", "USER: "))
        self.username_label.setText(_translate("admin_main", "USER1"))
        self.name_label.setText(_translate("admin_main", "NAME:"))
        self.nameuser_label.setText(_translate("admin_main", "NAME"))
        self.actionLogout.setText(_translate("admin_main", "Logout"))
        self.actionExit.setText(_translate("admin_main", "Exit"))


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    adminmainpage = QtWidgets.QMainWindow()
    ui = Ui_admin_main()
    ui.setupUi(adminmainpage)
    adminmainpage.show()
    sys.exit(app.exec_())
