# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'modifyquestion.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3
import questionbank
import updatingdbq
import sys

class Ui_modify_question(object):
    def setupUi(self, modify_question):
        modify_question.setObjectName("modify_question")
        modify_question.resize(597, 312)
        self.centralwidget = QtWidgets.QWidget(modify_question)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(30, 20, 511, 111))
        self.groupBox.setObjectName("groupBox")
        self.textEdit = QtWidgets.QTextEdit(self.groupBox)
        self.textEdit.setGeometry(QtCore.QRect(20, 30, 471, 71))
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(60, 260, 461, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.save_question_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.save_question_button.setObjectName("save_question_button")
        self.horizontalLayout.addWidget(self.save_question_button)
        self.cancel_question_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.cancel_question_button.setObjectName("cancel_question_button")
        self.horizontalLayout.addWidget(self.cancel_question_button)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(30, 140, 511, 91))
        self.groupBox_2.setObjectName("groupBox_2")
        self.textEdit_2 = QtWidgets.QTextEdit(self.groupBox_2)
        self.textEdit_2.setGeometry(QtCore.QRect(20, 30, 471, 51))
        self.textEdit_2.setObjectName("textEdit_2")
        modify_question.setCentralWidget(self.centralwidget)

        self.retranslateUi(modify_question)
        QtCore.QMetaObject.connectSlotsByName(modify_question)
        #########################################
        self.cancel_question_button.clicked.connect(modify_question.close)
        self.cancel_question_button.clicked.connect(self.showquestionbank)
      #  self.save_question_button.clicked.connect(self.showquestionbank)
        self.save_question_button.clicked.connect(modify_question.close)
        self.save_question_button.clicked.connect(self.showupdatingdb)
    
    def showupdatingdb(self):
        self.updatingdbWindow = QtWidgets.QMainWindow()
        self.ui = updatingdbq.Ui_updatedbq()
        self.ui.setupUi(self.updatingdbWindow)
        self.updatingdbWindow.show() 
 
        question = self.textEdit.toPlainText()
        answer = self.textEdit_2.toPlainText()
        try:
            con = sqlite3.connect("userlist.db",timeout=10)
            cur = con.cursor()
            cur.execute('SELECT * from questionbank WHERE ID =2')
            one = cur.fetchall()
            con.commit()
            for row in one:
                modify = row[3]
            print(question)
            print(answer)

            cur.execute('UPDATE questionbank SET QUESTION = ?, ANSWER = ? WHERE ID= 2',(question,answer,))
            con.commit()
            cur.execute('UPDATE questionbank SET QUESTION = ?, ANSWER = ? WHERE ID= ?',(question,answer,modify,))

            con.commit()
        except Exception:
            self.showMessageBox('Database Error','Could not access the database')

    def showquestionbank(self):
        self.questionbankwindow = QtWidgets.QMainWindow()
        self.ui = questionbank.Ui_Question_bank()
        self.ui.setupUi(self.questionbankwindow)
        self.questionbankwindow.show()

    def showMessageBox(self,title,message):
        msgBox = QtWidgets.QMessageBox()
        msgBox.setIcon(QtWidgets.QMessageBox.Warning)
        msgBox.setWindowTitle(title)
        msgBox.setText(message)
        msgBox.setStandardButtons(QtWidgets.QMessageBox.Ok)
        msgBox.exec_()

    def retranslateUi(self, modify_question):
        _translate = QtCore.QCoreApplication.translate
        modify_question.setWindowTitle(_translate("modify_question", "Modify Question"))
        self.groupBox.setTitle(_translate("modify_question", "Question"))
        self.save_question_button.setText(_translate("modify_question", "Save"))
        self.cancel_question_button.setText(_translate("modify_question", "Cancel"))
        self.groupBox_2.setTitle(_translate("modify_question", "Answer"))

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    modifyquestion = QtWidgets.QMainWindow()
    ui = Ui_modify_question()
    ui.setupUi(modifyquestion)
    modifyquestion.show()
    sys.exit(app.exec_())