# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'performanceassesment.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import StudentTestAnswer
import sqlite3
import studentmain


class Ui_performanceassesment(object):
    def setupUi(self, performanceassesment):
        performanceassesment.setObjectName("performanceassesment")
        performanceassesment.resize(384, 190)
        self.centralwidget = QtWidgets.QWidget(performanceassesment)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(30, 20, 331, 141))
        self.groupBox.setObjectName("groupBox")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setGeometry(QtCore.QRect(40, 90, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(200, 90, 93, 28))
        self.pushButton.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(90, 40, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        performanceassesment.setCentralWidget(self.centralwidget)

        try:
            con = sqlite3.connect("userlist.db",timeout=10)
            cur = con.cursor()
            cur.execute('SELECT MODIFY FROM questionbank WHERE ID=1')
            data = cur.fetchall()
            for row in data:
                score = row[0]
            con.commit()
            print(score)
            if score == 0:
                self.label.setText("VERY BAD")
            elif score == 15: 
                self.label.setText("PERFECT")
            elif score < 15 and score > 10:
                self.label.setText("GOOD")
            elif score < 10 and score > 5:
                self.label.setText("AVERAGE")
            elif score < 5:
                self.label.setText("BAD")
            
        except Exception:
            self.showMessageBox('Database Error','Could not access the database')

        self.retranslateUi(performanceassesment)
        QtCore.QMetaObject.connectSlotsByName(performanceassesment)
        #######################
        self.pushButton.clicked.connect(self.studentmainshow)
        self.pushButton.clicked.connect(performanceassesment.close)
        ######################
        self.pushButton_2.clicked.connect(self.StudentTestAnswerShow)
        self.pushButton_2.clicked.connect(performanceassesment.close)
    
    def StudentTestAnswerShow(self):
        self.StudentTestAnswerWindow = QtWidgets.QMainWindow()
        self.ui = StudentTestAnswer.Ui_ReviewerTest()
        self.ui.setupUi(self.StudentTestAnswerWindow)
        self.StudentTestAnswerWindow.show()
    
    def studentmainshow(self):
        self.StudentTestAnswerWindow = QtWidgets.QMainWindow()
        self.ui = studentmain.Ui_student_main()
        self.ui.setupUi(self.StudentTestAnswerWindow)
        self.StudentTestAnswerWindow.show()
    
    
    def showMessageBox(self,title,message):
        msgBox = QtWidgets.QMessageBox()
        msgBox.setIcon(QtWidgets.QMessageBox.Warning)
        msgBox.setWindowTitle(title)
        msgBox.setText(message)
        msgBox.setStandardButtons(QtWidgets.QMessageBox.Ok)
        msgBox.exec_()


    def retranslateUi(self, performanceassesment):
        _translate = QtCore.QCoreApplication.translate
        performanceassesment.setWindowTitle(_translate("performanceassesment", "Performance Assessment"))
        self.groupBox.setTitle(_translate("performanceassesment", "Performance Assessment"))
        self.pushButton_2.setText(_translate("performanceassesment", "RETRY"))
        self.pushButton.setText(_translate("performanceassesment", "OK"))
        #self.label.setText(_translate("performanceassesment", "BAD!"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    performanceasses = QtWidgets.QMainWindow()
    ui = Ui_performanceassesment()
    ui.setupUi(performanceasses)
    performanceasses.show()
    sys.exit(app.exec_())