# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'studentinfo.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3
import studentlist
import sys
import modifystudent_name
import modifystudent_password
import modifystudent_username
import updatingdb

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(490, 203)
        MainWindow.setMinimumSize(QtCore.QSize(490, 203))
        MainWindow.setMaximumSize(QtCore.QSize(490, 203))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 451, 121))
        self.groupBox.setObjectName("groupBox")
        self.user_student_label = QtWidgets.QLabel(self.groupBox)
        self.user_student_label.setGeometry(QtCore.QRect(20, 30, 55, 16))
        self.user_student_label.setObjectName("user_student_label")
        self.name_student_label = QtWidgets.QLabel(self.groupBox)
        self.name_student_label.setGeometry(QtCore.QRect(20, 60, 55, 16))
        self.name_student_label.setObjectName("name_student_label")
        self.password_student_label = QtWidgets.QLabel(self.groupBox)
        self.password_student_label.setGeometry(QtCore.QRect(20, 90, 81, 16))
        self.password_student_label.setObjectName("password_student_label")
        self.user_student = QtWidgets.QLabel(self.groupBox)
        self.user_student.setGeometry(QtCore.QRect(100, 30, 201, 16))
        self.user_student.setObjectName("user_student")
        self.name_student = QtWidgets.QLabel(self.groupBox)
        self.name_student.setGeometry(QtCore.QRect(100, 60, 201, 16))
        self.name_student.setObjectName("name_student")
        self.password_student = QtWidgets.QLabel(self.groupBox)
        self.password_student.setGeometry(QtCore.QRect(100, 90, 201, 16))
        self.password_student.setObjectName("password_student")
        self.change_user_button = QtWidgets.QPushButton(self.groupBox)
        self.change_user_button.setGeometry(QtCore.QRect(320, 20, 93, 28))
        self.change_user_button.setObjectName("change_user_button")
        self.change_name_button = QtWidgets.QPushButton(self.groupBox)
        self.change_name_button.setGeometry(QtCore.QRect(320, 50, 93, 28))
        self.change_name_button.setObjectName("change_name_button")
        self.change_password_button = QtWidgets.QPushButton(self.groupBox)
        self.change_password_button.setGeometry(QtCore.QRect(320, 80, 93, 28))
        self.change_password_button.setObjectName("change_password_button")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 140, 451, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.save_students_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.save_students_button.setObjectName("save_students_button")
        self.horizontalLayout.addWidget(self.save_students_button)
        self.canel_students_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.canel_students_button.setObjectName("canel_students_button")
        self.horizontalLayout.addWidget(self.canel_students_button)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        ##############################################################################
        self.canel_students_button.clicked.connect(MainWindow.close)
        self.canel_students_button.clicked.connect(self.showstudentlist)
        self.save_students_button.clicked.connect(MainWindow.close)
        self.save_students_button.clicked.connect(self.showstudentlist)
        ##############################################################################
        self.change_name_button.clicked.connect(self.showmodifyname)
        self.change_name_button.clicked.connect(MainWindow.close)
        self.change_password_button.clicked.connect(self.showmodifypassword)
        self.change_password_button.clicked.connect(MainWindow.close)
        self.change_user_button.clicked.connect(self.showmodifyusername)
        self.change_user_button.clicked.connect(MainWindow.close)
        try:
            con = sqlite3.connect("userlist.db",timeout=10)
            cur = con.cursor()
            cur.execute('SELECT * FROM users WHERE ID=2')
            data = cur.fetchall()
            con.commit
            for row in data:
                usertype = row[1]
                name = row[2]
                username1 = row[3]
                password1 = row[4]
            con.close
            self.user_student.setText(username1)
            self.name_student.setText(name)
            self.password_student.setText(password1)
        except Exception:
            self.showMessageBox('Database Error','Could not access the database')

    def showstudentlist(self):
        self.studentlistWindow = QtWidgets.QMainWindow()
        self.ui = studentlist.Ui_MainWindow()
        self.ui.setupUi(self.studentlistWindow)
        self.studentlistWindow.show() 

    def showmodifyusername(self):
        self.modifyusernameWindow = QtWidgets.QMainWindow()
        self.ui = modifystudent_username.Ui_modifystudent_username()
        self.ui.setupUi(self.modifyusernameWindow)
        self.modifyusernameWindow.show()

    def showmodifyname(self):
        self.modifynameWindow = QtWidgets.QMainWindow()
        self.ui = modifystudent_name.Ui_modifystudent_name()
        self.ui.setupUi(self.modifynameWindow)
        self.modifynameWindow.show()

    def showmodifypassword(self):
        self.modifypassWindow = QtWidgets.QMainWindow()
        self.ui = modifystudent_password.Ui_modifystudent_password()
        self.ui.setupUi(self.modifypassWindow)
        self.modifypassWindow.show()   

    def showupdatingdb(self):
        self.updatingdbWindow = QtWidgets.QMainWindow()
        self.ui = updatingdb.Ui_updatedb()
        self.ui.setupUi(self.updatingdbWindow)
        self.updatingdbWindow.show()   

    def showMessageBox(self,title,message):
        msgBox = QtWidgets.QMessageBox()
        msgBox.setIcon(QtWidgets.QMessageBox.Warning)
        msgBox.setWindowTitle(title)
        msgBox.setText(message)
        msgBox.setStandardButtons(QtWidgets.QMessageBox.Ok)
        msgBox.exec_()


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Student Information"))
        self.groupBox.setTitle(_translate("MainWindow", "Student Information"))
        self.user_student_label.setText(_translate("MainWindow", "USER:"))
        self.name_student_label.setText(_translate("MainWindow", "NAME:"))
        self.password_student_label.setText(_translate("MainWindow", "PASSWORD:"))
        self.user_student.setText(_translate("MainWindow", "USER1"))
        self.name_student.setText(_translate("MainWindow", "NAME1"))
        self.password_student.setText(_translate("MainWindow", "PASS1"))
        self.change_user_button.setText(_translate("MainWindow", "change"))
        self.change_name_button.setText(_translate("MainWindow", "change"))
        self.change_password_button.setText(_translate("MainWindow", "change"))
        self.save_students_button.setText(_translate("MainWindow", "Save"))
        self.canel_students_button.setText(_translate("MainWindow", "Cancel"))


if __name__ == "__main__":
        app = QtWidgets.QApplication(sys.argv)
        studentinfo = QtWidgets.QMainWindow()
        ui = Ui_MainWindow()
        ui.setupUi(studentinfo)
        studentinfo.show()
        sys.exit(app.exec_())