# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'updatingdbq.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3
import questionbank
import sys

class Ui_updatedbq(object):
    def setupUi(self, updatedbq):
        updatedbq.setObjectName("updatedbq")
        updatedbq.resize(315, 97)
        self.centralwidget = QtWidgets.QWidget(updatedbq)
        self.centralwidget.setObjectName("centralwidget")
        self.ok_button = QtWidgets.QPushButton(self.centralwidget)
        self.ok_button.setGeometry(QtCore.QRect(110, 60, 93, 28))
        self.ok_button.setObjectName("ok_button")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 20, 151, 16))
        self.label.setObjectName("label")
        updatedbq.setCentralWidget(self.centralwidget)
        self.ok_button.clicked.connect(self.showquestionbank)
        self.ok_button.clicked.connect(updatedbq.close)
        try:
            con = sqlite3.connect("userlist.db",timeout=10)
            cur = con.cursor()
            cur.execute('SELECT * from questionbank WHERE ID =2')
            one = cur.fetchall()
            con.commit()
            for row in one:
                modify = row[3]
            print(modify)
            cur.execute('SELECT * from questionbank WHERE ID =?',(modify,))
            data2 = cur.fetchall()
            for row in data2:
                question = row[1]
                answer = row[2]
            cur.execute('UPDATE questionbank SET QUESTION=?, ANSWER=? WHERE ID=?',(question,answer,modify,))
            con.commit()
            con.close()
        except Exception:
            self.showMessageBox('Database Error','Could not access the database')

        self.retranslateUi(updatedbq)
        QtCore.QMetaObject.connectSlotsByName(updatedbq)


    def showMessageBox(self,title,message):
        msgBox = QtWidgets.QMessageBox()
        msgBox.setIcon(QtWidgets.QMessageBox.Warning)
        msgBox.setWindowTitle(title)
        msgBox.setText(message)
        msgBox.setStandardButtons(QtWidgets.QMessageBox.Ok)
        msgBox.exec_()

    def showquestionbank(self):
        self.questionbankwindow = QtWidgets.QMainWindow()
        self.ui = questionbank.Ui_Question_bank()
        self.ui.setupUi(self.questionbankwindow)
        self.questionbankwindow.show()   

    def retranslateUi(self, updatedbq):
        _translate = QtCore.QCoreApplication.translate
        updatedbq.setWindowTitle(_translate("updatedbq", "Database"))
        self.ok_button.setText(_translate("updatedbq", "Ok"))
        self.label.setText(_translate("updatedbq", "Updating the Database..."))


if __name__ == "__main__":
        app = QtWidgets.QApplication(sys.argv)
        updatedb = QtWidgets.QMainWindow()
        ui = Ui_updatedbq()
        ui.setupUi(updatedb)
        updatedb.show()
        sys.exit(app.exec_())