# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'updatingdbuser.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import studentinfo
import sqlite3

class Ui_updatingdbuser(object):
    def setupUi(self, updatingdbuser):
        updatingdbuser.setObjectName("updatingdbuser")
        updatingdbuser.resize(314, 97)
        self.centralwidget = QtWidgets.QWidget(updatingdbuser)
        self.centralwidget.setObjectName("centralwidget")
        self.ok_button = QtWidgets.QPushButton(self.centralwidget)
        self.ok_button.setGeometry(QtCore.QRect(110, 60, 93, 28))
        self.ok_button.setObjectName("ok_button")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 20, 151, 16))
        self.label.setObjectName("label")
        updatingdbuser.setCentralWidget(self.centralwidget)
        #################################################################
        try:
            con = sqlite3.connect("userlist.db",timeout=10)
            cur = con.cursor()
            cur.execute('SELECT * from users WHERE ID =2')
            one = cur.fetchall()
            con.commit()
            for row in one:
                modify = row[5]
            print(modify)
            cur.execute('SELECT * from users WHERE ID =?',(modify,))
            data2 = cur.fetchall()
            for row in data2:
                usertype = row[1]
                name = row[2]
                username1 = row[3]
                password1 = row[4]
            cur.execute('UPDATE users SET TYPE=?,NAME=?,USERNAME=?,PASSWORD=? WHERE ID=?',(usertype,name,username1,password1,modify))
            con.commit()
            con.close()
        except Exception:
            self.showMessageBox('Database Error','Could not access the database')
        ######################################################
        self.retranslateUi(updatingdbuser)
        QtCore.QMetaObject.connectSlotsByName(updatingdbuser)
        #######################################################
        self.ok_button.clicked.connect(self.showstudentinfo)
        self.ok_button.clicked.connect(updatingdbuser.close)

    def showstudentinfo(self):
        self.studentinfoWindow = QtWidgets.QMainWindow()
        self.ui = studentinfo.Ui_MainWindow()
        self.ui.setupUi(self.studentinfoWindow)
        self.studentinfoWindow.show()
    
    def showMessageBox(self,title,message):
        msgBox = QtWidgets.QMessageBox()
        msgBox.setIcon(QtWidgets.QMessageBox.Warning)
        msgBox.setWindowTitle(title)
        msgBox.setText(message)
        msgBox.setStandardButtons(QtWidgets.QMessageBox.Ok)
        msgBox.exec_()

    def retranslateUi(self, updatingdbuser):
        _translate = QtCore.QCoreApplication.translate
        updatingdbuser.setWindowTitle(_translate("updatingdbuser", "Database"))
        self.ok_button.setText(_translate("updatingdbuser", "Ok"))
        self.label.setText(_translate("updatingdbuser", "Updating the Database..."))


if __name__ == "__main__":
        app = QtWidgets.QApplication(sys.argv)
        updatedb = QtWidgets.QMainWindow()
        ui = Ui_updatingdbuser()
        ui.setupUi(updatedb)
        updatedb.show()
        sys.exit(app.exec_())